# Model IDs from Hugging Face
models:
  text_to_image: "black-forest-labs/FLUX.1-Kontext-dev"
  image_to_image: "black-forest-labs/FLUX.1-Kontext-dev"
  nunchaku_transformer: "mit-han-lab/nunchaku-flux.1-kontext-dev/svdq-int4_r32-flux.1-kontext-dev.safetensors"

# Default generation parameters for the UI
defaults:
  t2i:
    steps: 28
    guidance: 4.0
  i2i:
    steps: 28
    guidance: 3.0

# LLM providers for the prompt enhancer
# Only providers with working implementations are included
enhancer_providers:
  - "Qwen-VL-Max (Alibaba Cloud)"  # ✅ Premier vision + text enhancement

# API-based model configurations
api_models:
  # Black Forest Labs (Original Pro API)
  bfl_flux_t2i:
    api_base: "https://api.bfl.ai"
    model_name: "flux-1-kontext-pro"
    endpoint: "/v1/flux-kontext-pro"
  bfl_flux_i2i:
    api_base: "https://api.bfl.ai"
    model_name: "flux-1-kontext-pro"
    endpoint: "/v1/flux-kontext-pro"
  # GRS AI Flux (Cost-effective alternative - 100% Flux API compatible)
  grs_flux_t2i:
    api_base: "https://api.grsai.com"
    model_name: "flux-1-kontext-pro"
    endpoint: "/v1/flux-kontext-pro"
  grs_flux_i2i:
    api_base: "https://api.grsai.com"
    model_name: "flux-1-kontext-pro"
    endpoint: "/v1/flux-kontext-pro"